# yaml 配置
version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      labels:
        - "by docker-compose build"
      target: prod
    ports:
      - "81:80"
    command: supervisord -c /etc/supervisord.conf
